# Generated by Django 4.2.7 on 2023-11-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='file',
            field=models.FileField(default='newfile.txt', upload_to=''),
        ),
        migrations.AddField(
            model_name='journal',
            name='image',
            field=models.ImageField(default='image.png', upload_to=''),
        ),
    ]
