# Generated by Django 4.2.7 on 2023-11-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_file_journal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='file',
        ),
        migrations.AddField(
            model_name='journal',
            name='audio_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='journal',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
