# Generated by Django 4.2.7 on 2023-11-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_journal_file_journal_audio_file_journal_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.TextField(),
        ),
    ]
