# Generated by Django 4.2.7 on 2023-11-05 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0005_journal_data_alter_journal_date_alter_journal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal',
            name='data',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='journal',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
