# Generated by Django 4.2.7 on 2023-11-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_journal_user_alter_journal_data_alter_journal_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
